type Product {
  id: ID!
  name: String!
  imageUrl: URL
  price: ProductPrice!
}

type ProductPrice {
  value: Int!
  currency: String!
}

extend type Query {
  allProducts: [Product]
  productById(id: ID!): Product
}
