type Event {
  id: ID!
  title: String
  description: String
  location: String
  ical: URL
  start: DateTime
  end: DateTime
}

input EventOrderInput {
  field: String!
  reverse: Boolean
}

extend type Query {
  event(id: ID!): Event
  events(count: Int, order: EventOrderInput): [Event!]!
}